### PR TITLE
Image refactor

### PR DESCRIPTION
**Pull request by freeman-lab**
This PR refactors the leaflet-based image viewing visualizations in lightning in two ways. cc @mathisonian @poolio @pkaifosh

1) Splits functionality into two visualizations: a basic image viewer `image` , and a visualization that allows drawing regions on top of the image called `image-draw`

2) The `image-draw` visualization now can be initialized with a set of polygon coordinates as inputs

For the latter, the input can either be a simple array of region-bounding coordinates (one subarray per region), or a `FeatureCollection` containing polygons in [geojson](http://geojson.org/geojson-spec.html#polygon) format, which will be checked and validated during data parsing using the `geojson-validation` node package.

Two outstanding issues that might be worth getting input on / trying to fix before merging are:

1) There's new functionality to vary the stroke / fill color of all points using `shift+arrow` key commands. This works nicely, but only on existing regions, not new ones that are created. Can this be improved through more clever css manipulation? I bet @mathisonian has a hack =)

2) Related to the above point, there is no way to specify a separate color for each of the initializing regions, which might be useful. An alternative is to render the initializing regions directly as Leaflet objects (rather than go through freeDraw's `createPolygon` method), which would give much more control over colors, etc. But then the existing regions would not be editable in the way that the new ones are.

image-draw

### CODE REVIEW

**Comment by mathisonian** [comment]
This looks great! Let me go through and I'll see if there's a good solution for (1). I suppose it would be nice to keep in the spirit of the other visualizations and allow for an array of initial color values. How would the interaction for updating colors post-hoc look in that case?

**Comment by freeman-lab** [comment]
Yeah, completely agree we want to support an array of either colors or labels. See if you can find an easy way to do that, probably not with css... 

As for the interactivity then, how about the shift-arrow cycles between the following four states:
- all regions are white
- all regions are some bright color (let's go with purple)
- all regions are what they were assigned in `data.colors`, and otherwise (if they are new) white
- all regions are what they were assigned in `data.colors`, and otherwise (if they are new) purple

(Thanks to @sofroniewn for this suggestion!)

**Comment by freeman-lab** [comment]
@mathisonian your updates were sweet! Just made a couple final tweaks: color handling is now more like the other viz types (assumes either RGB values or labels), and the default is to automatically populate each region with a different color (like the line plot). And I also dropped mode 4, because after playing around, I thought the mix of colored regions and bright colored regions was kinda confusing, and also cycling through four different color modes was confusing when, in some circumstances, two of the four looked identical. If you're on board I'll merge this in!

**Comment by freeman-lab** [comment]
Hmm... one other thing we might need to fix, if you start from, say, the sample data and start deleting regions, the colors start changing, seemingly randomly? And once you've deleted a bunch, and draw new ones, they have the colors of the old ones. Ideally, deleting a region would have no effect on the colors of the others, and any new regions are always colorless.

**Comment by freeman-lab** [comment]
Just fixed the updating behavior so regions persist, I'm going to merge this version in so we can do some testing with it, and we can fix the color updating after deletion in a follow-up.

**Pull request merged**
